# Use this in your UnturnedImages/config.yaml file
- Id: "50050-50054;50061-50063;50100-50202" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3304904264/vehicles/{ItemId}.png" # The repository of the override.