# Use this in your UnturnedImages/config.yaml file
- Id: "53200" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3338182303/vehicles/{ItemId}.png" # The repository of the override.